---
- hosts: all
  become: true

###
### Base (for every machine)
###
- hosts: all
  tags: base
  become: true
  roles:
    - base

###
### Only workstations
###
- hosts: workstations
  tags: workstations
  become: true
  roles:
    - workstations

###
### Only proxmox
###
- hosts: proxmox
  tags: proxmox
  become: true
  roles:
    - proxmox


###
### Only proxmox
###
- hosts: servers
  tags: servers
  become: true
  roles:
    - servers

###
### end of run cleanup and reporting
###
- hosts: all
  become: true
  tasks:
    - name: Cleanup package cache (debian and ubuntu)
      tags: always
      apt:
        autoclean: true
      changed_when: false
      when: ansible_pkg_mgr == "apt"

    - name: Autoremove orphan packages (debian and ubuntu)
      tags: always
      apt:
        autoremove: true
        purge: true
      when: ansible_pkg_mgr == "apt"
