- name: Add quiet intel_iommu=on to kernel cmdline
  tags: proxmox,iommu
  lineinfile:
    path: /etc/kernel/cmdline
    backrefs: true
    regexp: '^(((?!quiet intel_iommu=on).)*)$'
    line: '\1 quiet intel_iommu=on'
    state: present
  notify: proxmox-boot-tool

  # inspired from galexrt/ansible-kernel-modules
- name: Add kernel modules to autoload file
  tags: proxmox,iommu
  lineinfile:
    create: yes
    dest: "/etc/modules-load.d/load-ansible.conf"
    line: "{{ item }}"
    state: present
    owner: root
    group: root
    mode: 0644
  with_items:
      - vfio
      - vfio_iommu_type1
      - vfio_pci
      - vfio_virqfd
  notify:
    - restart systemd-modules-load

