---
- name: apt_update
  apt: update_cache=yes

- name: restart_sshd
  service:
    name: "{{ openssh_service }}"
    state: restarted

# handlers file for ohmyzsh
- name: Configure .zshrc
  copy:
    src: ~/.oh-my-zsh/templates/zshrc.zsh-template
    dest: ~/.zshrc
    mode: '0644'
    remote_src: yes
  become: yes
  become_user: "{{ item }}"
  with_items: "{{ ohmyzsh_users }}"

# handler for Netplan
- name: Apply Netplan
  ansible.builtin.command:
    cmd: netplan apply
  become: yes
  tags: dns
