---
- name: apt_update
  apt: update_cache=yes

- name: restart_sshd
  service:
    name: "{{ openssh_service }}"
    state: restarted

# handlers file for ohmyzsh
- name: Configure .zshrc
  copy:
    src: ~/.oh-my-zsh/templates/zshrc.zsh-template
    dest: ~/.zshrc
    mode: '0644'
    remote_src: yes
  become: yes
  become_user: "{{ item }}"
  with_items: "{{ ohmyzsh_users }}"

# handler for Netplan
- name: Apply Netplan
  ansible.builtin.command:
    cmd: netplan apply
  become: yes
  tags: dns

- name: Ansible Setup | Reboot the node
  ansible.builtin.reboot:
    reboot_timeout: 600
  when: ansible_distribution != "Proxmox"
  # This handler reboots the node using the 'ansible.builtin.reboot' module.
  # The 'reboot_timeout' sets the maximum time (in seconds) to wait for the system to reboot and reconnect.
  # The task checks if the node is not a Proxmox host before rebooting, as Proxmox nodes generally manage reboots differently.
