---
- name: Update Repo's
  ansible.builtin.apt:
    update_cache: true

- name: Restart_sshd
  ansible.builtin.service:
    name: "{{ openssh_service }}"
    state: restarted

# handlers file for ohmyzsh
- ansible.builtin.name: Configure .zshrc
  copy:
    src: ~/.oh-my-zsh/templates/zshrc.zsh-template
    dest: ~/.zshrc
    mode: '0644'
    remote_src: true
  become: true
  become_user: "{{ item }}"
  with_items: "{{ ohmyzsh_users }}"

- name: Apply Netplan
  ansible.builtin.command:
    cmd: netplan apply
  become: true
  changed_when: false
  tags: dns
  # This handler applies Netplan configuration.
  # The 'changed_when: false' ensures that the task is not marked as "changed" if nothing needed to be applied.

- name: Ansible Setup | Reboot the node
  ansible.builtin.reboot:
    reboot_timeout: 600
  when: ansible_distribution != "Proxmox"
  # This handler reboots the node using the 'ansible.builtin.reboot' module.
  # The 'reboot_timeout' sets the maximum time (in seconds) to wait for the system to reboot and reconnect.
  # The task checks if the node is not a Proxmox host before rebooting, as Proxmox nodes generally manage reboots differently.
