---
# Handler for server playbooks
# Handlers for PiHole
- name: Restart Unbound services
  ansible.builtin.service:
    name: unbound
    state: restarted

- name: restart pihole-ftl
  systemd:
    name: pihole-FTL
    state: restarted

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

# Handlers for docker/docker_install.yml and docker/portainer_deploy.yml
# Restart Docker service
- name: Restart Docker
  ansible.builtin.systemd:
    name: docker
    state: restarted