---
# TODO: still needed?
- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

# Handlers for docker/docker_install.yml and docker/portainer_deploy.yml
# Restart Docker service
- name: Restart Docker
  ansible.builtin.systemd:
    name: docker
    state: restarted