# File: roles/samba/handlers/main.yml
---
- name: Restart Unbound services
  ansible.builtin.service:
    name: unbound
    state: restarted

- name: restart pihole-ftl
  systemd:
    name: pihole-FTL
    state: restarted

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
