---
- name: servers | portainer | create volume
  docker_volume:
    name: portainer_data

- name: servers | portainer | start portainer
  community.docker.docker_container:
    name: portainer
    image: "portainer/portainer-ce:latest"
    state: started
    restart: true
    restart_policy: "always"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
     - "8000:8000"
     - "9443:9443"


