---
# installing portainer on our docker_server

- name: Ensure Docker service is running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Setup Portainer directory
  ansible.builtin.file:
    path: /home/erwin/docker-compose/portainer
    state: directory
    mode: '0755'  # Optional file permissions
    owner: erwin  # Optional ownership
    group: erwin  # Optional group ownership

- name: Deploy Portainer using Docker Compose
  ansible.builtin.template:
    src: "templates/docker_compose_portainer.yaml.j2"
    dest: "/home/erwin/docker-compose/portainer/docker-compose.yaml"
    mode: '0755'  # Optional file permissions
    owner: erwin  # Optional ownership
    group: erwin  # Optional group ownership

# Restart Portainer service
- name: Start Portainer
  community.docker.docker_compose:
    project_src: /home/erwin/docker-compose/portainer
    state: present
    restarted: true