---
- name: servers | pihole | install pihole packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ pihole_packages }}"
  tags: pihole,packages

- name: servers | pihole | Check Pi-Hole is installed
  tags: pihole
  ansible.builtin.stat:
    path: "/usr/local/bin/pihole"
  register: pihole_binary

# https://codeberg.org/ansible/pihole

- name: servers | pihole | Setup pihole for installation
  tags: pihole
  ansible.builtin.import_tasks: setup.yml
  when: not pihole_binary.stat.exists

- name: servers | pihole | Install pihole from repo
  tags: pihole
  ansible.builtin.import_tasks: install.yml
  when: not pihole_binary.stat.exists

# https://git.zotha.de/ansible-roles/pihole
- name: servers | pihole | setup gravity-sync
  tags: pihole,gravity-sync
  include_tasks: gravity_sync.yml

- name: servers | pihole | installing custom list of local hosts in pihole
  tags: pihole
  copy:
    src: pihole/custom.list
    dest: /etc/pihole/custom.list
    owner: root
    group: root
    mode: 0644
  notify: restart pihole-ftl

- name: servers | pihole | installing unbound config
  tags: pihole,unbound
  copy:
    src: pihole/unbound-pi-hole.conf
    dest: /etc/unbound/unbound.conf.d/pi-hole.conf
    owner: root
    group: root
    mode: 0644
  notify:  Restart Unbound services    

- name: servers | pihole | removing the unbound-resolv service
  tags: pihole,unbound
  ansible.builtin.service:
    name: unbound-resolvconf
    state: stopped
