---
# Disable systemd-resolved and update resolv.conf
- name: Ensure the directory /etc/systemd/resolved.conf.d/ exists
  file:
    path: /etc/systemd/resolved.conf.d/
    state: directory
    mode: '0755'

- name: Deploy disable-stub.conf to disable systemd-resolved
  template:
    src: disable-stub.conf.j2
    dest: /etc/systemd/resolved.conf.d/disable-stub.conf
    mode: '0644'

- name: Create a symbolic link for resolv.conf
  file:
    src: /run/systemd/resolve/resolv.conf
    dest: /etc/resolv.conf
    state: link
    force: yes

- name: Restart systemd-resolved service
  systemd:
    name: systemd-resolved
    state: restarted

- name: Restart systemd-resolved service (again to ensure changes)
  systemd:
    name: systemd-resolved
    state: restarted
