pihole_packages:
  - unbound

docker_packages:
  - ca-certificates
  - curl
  - gnupg2
  - software-properties-common
  - python3-pip
  - virtualenv
  - python3-setuptools

docker_final_packages:
  - cifs-utils
  - docker-compose
    
# https://www.digitalocean.com/community/tutorials/how-to-use-ansible-to-install-and-set-up-docker-on-ubuntu-20-04
container_count: 4
default_container_name: docker
default_container_image: ubuntu
default_container_command: sleep 1
