---
# docker installation trough https://github.com/JamesTurland/JimsGarage/tree/main/Ansible/Playbooks/Docker-Portainer

docker_apt_release_channel: "stable"
docker_apt_repository: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
docker_daemon_options:
  storage-driver: "overlay2"

# portainer vars
portainer_version: "latest"

# pihole vars
pihole_version: "latest"
pihole_subnet: "172.23.0.0/16"
pihole_internal_ip: "172.23.0.7"
pihole_dns_resolver: "172.23.0.8"
pihole_unbound_version: "latest"

# syncthing vars
#
syncthing_packages:
  - curl
  - apt-transport-https
  - gnupg

# 
# Code Server variables
#
code_server_version: "latest"