- name: users | erwin | create group
  tags: groups,erwin,users
  group:
    name: erwin
    state: present

- name: users | erwin | create user
  tags: erwin,sudo,users,samba
  user:
    name: erwin
    group: erwin
    groups: adm,{{ sudo_group }},users
    state: present
    comment: "Erwin van de Glind"
    uid: 1001
    password: "{{ erwin_password | password_hash('sha512') }}"
    update_password: on_create

- name: users | erwin | erwin | add sudoers file
  tags: erwin,settings,simone,sudo,system,users
  copy:
    src: users/sudoers_erwin
    dest: /etc/sudoers.d/erwin
    owner: root
    group: root
    mode: 0440

- name: users | erwin | add public key
  tags: dotfiles,erwin,ssh,ssh-keys,users
  authorized_key:
    user: erwin
    key: "{{ item }}"
  with_file:
    - users/erwin/ssh/erwin_id_ed25519.pub
