---
- name: Neo Vim setup | Neo VIM | install nvim required packages
  tags: packages,nvim,vim
  package:
    state: latest
    name:
      - software-properties-common
      - nodejs
      - npm
      - python3-dev
      - python3-pip
      - python3.10-venv
  when:
    ansible_distribution == "Ubuntu"

    # NeoVIM wordt niet bijgehouden in de repo van Ubuntu
    # Moet dus handmatig geïnstalleerd worden, een PITA dus
- name: Neo Vim setup | Neo VIM | Remove Neo VIM from apt
  tags: packages,nvim,vim
  when: ansible_distribution == "Ubuntu"
  apt:
    update_cache: yes
    name: neovim
    state: absent

- name: Neo Vim setup | Neo VIM | Download Neo VIM v0.8.3
  tags: packages,nvim,vim
  get_url:
    url: "https://github.com/neovim/neovim/releases/download/{{ nvim_version }}/nvim-linux64.tar.gz"
    dest: "{{ download_dir }}/neovim-{{ nvim_version }}.tgz"
    checksum: "{{ nvim_checksum }}"

- name: Neo Vim setup | Neo VIM | Expand Neo VIM v0.8.3
  tags: packages,nvim,vim
  unarchive:
    src: "{{ download_dir }}/neovim-{{ nvim_version }}.tgz"
    dest: "{{ nvim_dir }}"
    remote_src: true
    creates: "{{ nvim_dir }}/nvim-linux64/bin/nvim"

- name: Neo Vim setup | Neo VIM | Set $PATH
  tags: packages,nvim,vim
  ansible.builtin.lineinfile:
    dest: /etc/environment
    state: present
    backrefs: yes
    regexp: 'PATH=(["]*)((?!.*?{{ nvim_dir }}/nvim-linux64/bin).*?)(["]*)$'
    line: 'PATH=\1\2:{{ nvim_dir }}/nvim-linux64/bin\3'

- name: Install "treesitter" node.js package globally.
  tags: packages,nvim,vim
  npm:
    name: tree-sitter-cli
    global: yes
