  # Bron: https://github.com/enix/ansible-proxmox-ve/blob/master/tasks/install-packages.yml
- name: System Setup | Proxmox | Repositories | Register repository signing key
  ansible.builtin.apt_key:
    url: "{{ proxmox_ve__apt_repo_key[ansible_distribution_release] }}"
  when: proxmox_server
  tags:
    - proxmox_server
    - bootstrap
  # This task registers the Proxmox repository signing key, which is required to verify the integrity of packages.
  # The key is fetched from the URL specified in the variable 'proxmox_ve__apt_repo_key', which is based on the distribution release.
  # The task only runs if 'proxmox_server' is set to true, ensuring it only applies to Proxmox servers.
  # The task is tagged with 'proxmox_server' and 'bootstrap' for targeted execution.

- name: System Setup | Proxmox | Repositories | Remove well-known repository files
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/{{ item }}
    state: absent
  with_items:
    - "{{ proxmox_ve__apt_repo_todel }}"
  when: proxmox_server
  tags:
    - proxmox_server
    - bootstrap
  # This task removes specific repository files listed in 'proxmox_ve__apt_repo_todel'.
  # The 'with_items' loop iterates over each item in the list, deleting the corresponding file in '/etc/apt/sources.list.d/'.
  # This is useful for cleaning up outdated or unwanted repository configurations on Proxmox servers.
  # The task only runs if 'proxmox_server' is set to true.
  # The task is tagged with 'proxmox_server' and 'bootstrap' for targeted execution.

- name: System Setup | Proxmox | Repositories | Add no-subscription repository
  ansible.builtin.apt_repository:
    repo: "{{ proxmox_ve__apt_repo_pve_no_subscription }}"
    state: present
    update_cache: true
  when: proxmox_server
  tags:
    - proxmox_server
    - bootstrap
  # This task adds the Proxmox no-subscription repository to the system's APT sources.
  # The repository URL is provided by the variable 'proxmox_ve__apt_repo_pve_no_subscription'.
  # The APT cache is updated after adding the repository to ensure that the package lists are current.
  # The task only runs if 'proxmox_server' is set to true.
  # The task is tagged with 'proxmox_server' and 'bootstrap' for targeted execution.

- name: System Setup | Proxmox | Repositories | Configure /etc/apt/sources.list using template
  template:
    src: templates/proxmox_sources.list.j2
    dest: /etc/apt/sources.list
  when: proxmox_server
  tags:
    - proxmox_server
    - bootstrap
  # This task configures the main APT sources list for the system using a template.
  # The template file 'proxmox_sources.list.j2' is used to create '/etc/apt/sources.list'.
  # This allows for consistent and customizable repository configurations on Proxmox servers.
  # The task only runs if 'proxmox_server' is set to true.
  # The task is tagged with 'proxmox_server' and 'bootstrap' for targeted execution.

- name: System Setup | Proxmox | Repositories | Apt-get update_cache (Proxmox)
  apt:
    update_cache: true
    cache_valid_time: 3600
  changed_when: false
  when:
    - proxmox_server
    - "'bootstrap' not in ansible_run_tags"
  # This task updates the APT cache on Proxmox servers if the 'proxmox_server' variable is true.
  # The task does not run if the 'bootstrap' tag is specified when running the playbook.
  # The 'changed_when: false' ensures that this task does not report any changes, even if it runs.
  # The 'when' condition ensures that the task only runs on Proxmox servers and only if the 'bootstrap' tag is not present.

- name: System Setup | Proxmox | Repositories | Full Update (BOOTSTRAP)
  apt:
    upgrade: dist
    update_cache: yes
  when:
    - "'bootstrap' in ansible_run_tags"
    - ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
    - proxmox_server
  tags: bootstrap
  # This task installs all available updates on Ubuntu and Debian systems.
  # The task only runs if the 'bootstrap' tag is specified when running the playbook.
  # The 'when' condition ensures that the task runs only on Ubuntu or Debian systems and only when the 'bootstrap' tag is present.
  # The 'apt' module performs a full system upgrade, and the cache is updated before the upgrade.
