- name: system setup | repositories | install package management tools (debian-based)
  tags: pre_tasks, packages, system, settings
  package:
    name:
      - aptitude
      - software-properties-common
      - apt-transport-https
    state: latest
  when: ansible_pkg_mgr == "apt"

  # Bron: https://github.com/enix/ansible-proxmox-ve/blob/master/tasks/install-packages.yml
- name: Register repository signing key
  tags: proxmox
  ansible.builtin.apt_key:
    url: "{{ proxmox_ve__apt_repo_key[ansible_distribution_release] }}"
  when: proxmox_server

- name: Removing well known repo files
  tags: proxmox
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/{{ item }}
    state: absent
  with_items:
    - "{{ proxmox_ve__apt_repo_todel }}"
  when: proxmox_server

- name: Add no-subscription repository
  tags: proxmox
  ansible.builtin.apt_repository:
    repo: "{{ proxmox_ve__apt_repo_pve_no_subscription }}"
    state: present
    update_cache: true
  when: proxmox_server

- name: Gebruik een template voor /etc/apt/sources.list
  tags: proxmox
  template:
    src: templates/proxmox_sources.list.j2
    dest: /etc/apt/sources.list

- name: Apt-get update_cache (Proxmox)
  tags:
    - always
    - proxmox
  apt:
    update_cache: true
    cache_valid_time: 3600
  changed_when: false
  when: proxmox_server
