- name: System Setup | Repositories | Install package management tools (debian-based)
  package:
    name:
      - aptitude
      - software-properties-common
      - apt-transport-https
    state: latest
  when: ansible_pkg_mgr == "apt"
  tags: bootstrap
  # This task installs essential package management tools on Debian-based systems.
  # The 'package' module ensures the listed packages are installed and up-to-date.
  # 'aptitude' provides an alternative package manager with additional functionality.
  # 'software-properties-common' adds tools to manage software repositories, including adding PPAs.
  # 'apt-transport-https' enables APT to use HTTPS repositories, which is important for security.
  # The task only runs if the package manager is 'apt', indicating a Debian-based system (like Debian or Ubuntu).
  # The 'bootstrap' tag allows this task to be specifically targeted during the initial setup phase.

- name: System Setup | Repositories | Install Updates (BOOTSTRAP)
  apt:
    upgrade: dist
    update_cache: yes
  when:
    - "'bootstrap' in ansible_run_tags"
    - ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
    - not proxmox_server
  tags: bootstrap
  # This task installs all available updates on Ubuntu and Debian systems.
  # The task only runs if the 'bootstrap' tag is specified when running the playbook.
  # The 'when' condition ensures that the task runs only on Ubuntu or Debian systems, 
  # and only when the 'bootstrap' tag is present, and when the system is not a Proxmox server.
  # The 'apt' module performs a full system upgrade, and the cache is updated before the upgrade.