- name: system setup | repositories | install package management tools (debian-based)
  tags: pre_tasks, packages, system, settings
  package:
    name:
      - aptitude
      - software-properties-common
      - apt-transport-https
    state: latest
  when: ansible_pkg_mgr == "apt"