- name: Create directory for RKE2 binary
  ansible.builtin.file:
    path: "{{ rke2_install_dir }}"
    state: directory
    mode: '0755'
  # This task creates a directory to download the RKE2 binary to.
  # The 'file' module is used to ensure that the directory exists with the specified permissions.

- name: Download RKE2 binary
  ansible.builtin.get_url:
    url: "{{ rke2_binary_url }}"
    dest: "{{ rke2_install_dir }}/rke2"
    mode: '0755'
  # This task downloads the RKE2 binary from the specified URL.
  # The 'get_url' module retrieves the binary and places it in the designated directory with executable permissions.

- name: Set executable permissions on the RKE2 binary
  ansible.builtin.file:
    path: "{{ rke2_install_dir }}/rke2"
    mode: '0755'
    state: file
  # This task ensures that the RKE2 binary has executable permissions.
  # The 'file' module sets the appropriate permissions on the binary to make it executable.
