---
- name: Base | Set timezone
  ansible.builtin.timezone:
    name: Europe/Amsterdam

- name: Base | Install common packages
  ansible.builtin.package:
    name:
      - curl
      - vim
      - git
      - htop
      - ca-certificates
    state: present

- name: Base | Ensure SSH service is running
  ansible.builtin.service:
    name: ssh
    enabled: true
    state: started

- name: Base | Ensure correct permissions on /tmp
  ansible.builtin.file:
    path: /tmp
    state: directory
    mode: "1777"
