- block:
  - name: send failure notification via telegram
    tags: always
    community.general.telegram:
      token: "{{ telegram_token }}"
      api_args:
        chat_id: "{{ telegram_chat_id }}"
        parse_mode: markdown
        text: "⚠️  Ansible provision failed on *{{ ansible_hostname }}*\n\n
        *Task*:  {{ ansible_failed_task.name }}\n
        *Action*: {{ ansible_failed_task.action }}\n
        *Error Message*: \n ```{{ ansible_failed_result | to_nice_json }}```"
        disable_web_page_preview: true
        disable_notification: true

  rescue:
    - name: send failure notification via telegram
      tags: always
      community.general.telegram:
        token: "{{ telegram_token }}"
        api_args:
          chat_id: "{{ telegram_chat_id }}"
          parse_mode: "markdown"
          text: "⚠️  Ansible provision failed on *{{ ansible_hostname }}*\n\n
          The specific error couldn't be shown, check the log."
          disable_web_page_preview: true
          disable_notification: true

