# Load distro-specific variables
- name: Include OS specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: servers

- block:
    - import_tasks: docker/docker_install.yml
      tags:
        - docker_install
        - docker_server
      when: docker_server
    - import_tasks: docker/portainer_deploy.yml
      tags:
        - portainer_server
      when: portainer_server
    - import_tasks: pihole/systemd-resolved.yml
      tags:
        - pihole_server
      when: pihole_server  
    - import_tasks: pihole/pihole_deploy.yml
      tags:
        - pihole_server
      when: pihole_server
    - import_tasks: syncthing/main.yml
      tags:
        - syncthing_server
      when: syncthing_server

  rescue:
    - set_fact: task_failed=true
