# Load distro-specific variables
- name: Include OS specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: servers

- block:
    - import_tasks: pihole/main.yml
      when: pihole_server
    - import_tasks: docker/docker_install.yml
      tags:
        - docker_install
        - docker
      when: docker_server
    - import_tasks: docker/portainer_deploy.yml
      tags:
        - portainer
      when: docker_server
    - import_tasks: syncthing/main.yml
      when: syncthing_server

  rescue:
    - set_fact: task_failed=true
