# Load distro-specific variables
- name: Include OS specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: servers  

- block:
  - import_tasks: pihole/main.yml
    when: pihole

  rescue:
    - set_fact: task_failed=true
