# Load distro-specific variables
- name: Include OS specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: servers

- block:
# load tasks for setting up Docker and Docker Compose for Ubuntu 24.04 LTS
    - import_tasks: docker/docker_install.yml
      tags:
        - docker_install
        - docker_server
      when: docker_server
# load tasks for setting up Portainer
    - import_tasks: portainer/portainer_deploy.yml
      tags:
        - portainer_server
      when: portainer_server
# load tasks for shutting off DNS resolver from system-resolved as port 53 will be needed for PiHole
    - import_tasks: pihole/systemd-resolved.yml
      tags:
        - pihole_server
      when: pihole_server 
# load tasks for setting up PiHole
    - import_tasks: pihole/pihole_deploy.yml
      tags:
        - pihole_server
      when: pihole_server
# load tasks for setting up Gravity Sync for PiHole
    - import_tasks: pihole/gravitysync_deploy.yml
      tags:
        - pihole_server
        - pihole_gravity
      when: pihole_gravity
# load tasks for setting up Syncthing
    - import_tasks: syncthing/main.yml
      tags:
        - syncthing_server
      when: syncthing_server
# load tasks for setting up Code-Server
    - import_tasks: code_server/main.yml
      tags:
        - code_server
      when: code_server

  rescue:
    - set_fact: task_failed=true
