- name: System setup | Openssh | Install or update daemon package
  tags: openssh,ssh,system,settings
  ansible.builtin.package:
    name: "{{ openssh_package }}"
    state: latest
  notify: Base Setup | Restart sshd

- name: System setup | Openssh | Enable daemon
  tags: openssh,ssh,system,settings
  ansible.builtin.service:
    name: "{{ openssh_service }}"
    enabled: true
    state: started

- name: System setup | Openssh | Generate sshd_config file from template
  tags: openssh,ssh,system,settings
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: "0600"
    validate: /usr/sbin/sshd -t -f %s
    backup: true
  notify: Base Setup | Restart sshd